### ISSUE TITLE
Pet Journal

### ISSUE THREAD

**Issue by F-I-R-E-F-O-X** [Phanx/Broker_LFG#1]
1x Broker_LFG\Addon.lua:234: attempt to call global 'TogglePetJournal' (a nil value)
Broker_LFG\Addon.lua:234: in function <Broker_LFG\Addon.lua:221>
Titan\LDBToTitan.lua:273: in function <Titan\LDBToTitan.lua:271>

Locals:
self = TitanPanelLFGButton {
 0 = <userdata>
 registry = <table> {
 }
}
button = "MiddleButton"
func = <function> defined @Broker_LFG\Addon.lua:221

**Comment by F-I-R-E-F-O-X** [comment]
This error occurs when middle clicking the broker button (if that wasn't obvious enough lol)

**Comment by Phanx** [comment]
This was fixed in 1742e3434b70a33b42c98af9abd3372e12401631 years ago
