### ISSUE TITLE
Openeing the Premade panel

### ISSUE THREAD

**Issue by 2ndHouse** [Phanx/Broker_LFG#2]
Would like to see a way to open the Premade panel directly from the plugin, maybe Alt-right clicking or something. What about also making all of these types of panels openable via a dropdown selection menu?

**Comment by Phanx** [comment]
I actually meant to add that in the last update, but apparently I got 
distracted and forgot...

**Comment by 2ndHouse** [comment]
Ah OK. Looking forward to update :D

**Comment by Phanx** [comment]
Premade Groups replaces Scenarios as the ctrl-click action in 7.0.3.1
