### ISSUE TITLE
Right click in instance does not work! 

### ISSUE THREAD

**Issue by TBABlackPanther** [Phanx/Broker_LFG#5]
Hello when I am in an LFR Group in the raid instance, iam not able to right click at the icon to leave the instance or group? The menu does not open! And i got this error: 

67x Broker_LFG\Addon.lua:159: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: in function `PlaySound'
Broker_LFG\Addon.lua:159: in function `OnClick'
Bazooka\Bazooka-v2.8.4.lua:1417: in function <Bazooka\Bazooka.lua:1414>

Locals:
(*temporary) = "igMainMenuOpen"
 any ideas?

**Comment by Phanx** [comment]
Fixed. The addon was already fixed; I just forgot to publish a release version, oops.
