### ISSUE TITLE
Lua error when you click the broker icon

### ISSUE THREAD

**Issue by yoshimo** [Phanx/Broker_LFG#6]
`
Count: 1
Message: ..\AddOns\Broker_LFG\Addon.lua line 159:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
`

**Comment by Phanx** [comment]
That was fixed almost a year ago: b6df8ffd95d74e6aa9e53014d056cf12ef3446ef
